name: Keep fork in sync
on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 10 * * *'
    - cron: '0 14 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  sync:
    uses: ryan-newinsights/github-workflows/.github/workflows/fork-sync.yml@main
    permissions:
      contents: write
    with:
      upstream_repo: ricequant/rqalpha
      branch: master
      strategy: rebase
